---
- name: Reboot hosts if required (Debian except PVE hosts)
  hosts: debian:!pve_hosts
  become: true

  tasks:
  - name: Check if reboot is required
    ansible.builtin.stat:
      path: /var/run/reboot-required
    register: reboot_required

  - name: Reboot the host
    ansible.builtin.reboot:
    when: reboot_required.stat.exists